// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class Announcement
    {
        public int AnnouncementId { get; set; }
        public string Announcement1 { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int BonusForFocus { get; set; }
        public int BonusForShopping { get; set; }
    }
}