// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class Employee
    {
        public int EmpId { get; set; }
        public bool EmpPermission { get; set; }
        public string EmpName { get; set; }
        public string EmpAccount { get; set; }
        public string EmpPassword { get; set; }
        public bool? Available { get; set; }
    }
}