// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class FocusSlide
    {
        public int FocusId { get; set; }
        public string Category { get; set; }
        public string ImagePath { get; set; }
        public string AudioPath { get; set; }
    }
}