// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int CartProductQuantity { get; set; }

        public virtual ProductOrder Order { get; set; }
        public virtual Product Product { get; set; }
    }
}