// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class PointHistory
    {
        public string PointDetailId { get; set; }
        public int MemberId { get; set; }
        public string ModifiedSource { get; set; }
        public int ModifiedAmount { get; set; }

        public virtual Member Member { get; set; }
    }
}