// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class ProductOrder
    {
        public ProductOrder()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        public int OrderId { get; set; }
        public int MemberId { get; set; }
        public bool OrderPayment { get; set; }
        public int OrderTotalPrice { get; set; }
        public bool OrderDelivery { get; set; }
        public string OrderAddress { get; set; }
        public DateTime OrderDate { get; set; }
        public string OrderNote { get; set; }
        public string OrderState { get; set; }

        public virtual Member Member { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}