// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class PurchaseDetail
    {
        public int PurchaseId { get; set; }
        public int ProductId { get; set; }
        public int PurchaseQuantity { get; set; }
        public int PurchasePrice { get; set; }

        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}