// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class Purchase
    {
        public Purchase()
        {
            PurchaseDetail = new HashSet<PurchaseDetail>();
        }

        public int PurchaseId { get; set; }
        public int SupplierId { get; set; }
        public string PurchaseNote { get; set; }
        public DateTime PurchaseDate { get; set; }

        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetail { get; set; }
    }
}