// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class Supplier
    {
        public Supplier()
        {
            Product = new HashSet<Product>();
            Purchase = new HashSet<Purchase>();
        }

        public int SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string SupplierTel { get; set; }
        public string SupplierAddress { get; set; }

        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}