// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class TarotOrder
    {
        public string TarotOrderId { get; set; }
        public int MemberId { get; set; }
        public string CardResult { get; set; }
        public string DivinationChat { get; set; }
        public DateTime TarotTime { get; set; }

        public virtual Member Member { get; set; }
    }
}