// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testAPI.Models
{
    public partial class TarotCard
    {
        public int TarotCardId { get; set; }
        public string TarotCardName { get; set; }
        public string TarotCardType { get; set; }
    }
}